-- Reusable permission templates ("modèles") admins can save per role and
-- apply directly to any worker from the redesigned Permissions screen.
create table if not exists public.permission_templates (
  id          uuid primary key default uuid_generate_v4(),
  name        text not null,
  role        text not null check (role in ('pompiste','chef_brigade','gerant','magasin')),
  permissions jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.permission_templates enable row level security;

create policy "permission_templates_all_authenticated"
  on public.permission_templates
  for all
  to authenticated
  using (true)
  with check (true);

-- Fix existing workers whose saved permissions were generated by the OLD
-- default template (before this change). Two corrections:
--
-- 1. Chef de brigade: "Brigades" créer was wrongly false — chiefs create their
--    own brigades as their core job, so the app now reads that flag directly
--    instead of hardcoding role checks. Without this, existing chiefs would
--    suddenly lose the "Créer Nouvelle Brigade" button after the update.
update public.brigade_chefs
set permissions = jsonb_set(permissions, '{Brigades,creer}', 'true'::jsonb)
where permissions ? 'Brigades'
  and coalesce((permissions->'Brigades'->>'creer')::boolean, false) = false;

-- 2. Gérant: "Brigades" was wrongly saved as full access (creer/modifier/
--    supprimer all true) even though the UI never actually allowed a gérant
--    to create, edit or delete a brigade. The app now reads these flags
--    directly, so existing gérant permission rows must be corrected to match
--    the real (view + print only) behavior they already had.
update public.gerants
set permissions = jsonb_set(
  jsonb_set(
    jsonb_set(permissions, '{Brigades,creer}', 'false'::jsonb),
    '{Brigades,modifier}', 'false'::jsonb
  ),
  '{Brigades,supprimer}', 'false'::jsonb
)
where permissions ? 'Brigades';
